In [2]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.12.0


In [3]:
dataset = tf.keras.datasets.mnist
print(dataset)

<module 'keras.api._v2.keras.datasets.mnist' from '/opt/anaconda3/envs/DL4Denv/lib/python3.11/site-packages/keras/api/_v2/keras/datasets/mnist/__init__.py'>


### virtualenv workflow

```bash
    python3 -m pip install --user virtualenv
    python3 -m virtualenv env_name # Create new virtual environment
    source env_name/bin/activate # Activate the Virtual Environment
    pip3 install jupyterlab notebook # Install Jupyter Notebook
    python3 -m ipykernel install --user --name=env_name # Create a Jupyter Kernel
    jupyter notebook # Start Jupyter Notebook
```

In [5]:
import numpy as np

In [11]:
my2D = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
my3D = np.array([
    [[1,2], [3,4]],
    [[5,6], [7,8]]
])
print(my2D)
print('----')
print(my3D)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
----
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [13]:
myMatrix = np.mat([[1,2,3], [4,5,6], [7,8,9]])
print(myMatrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
