<table class="tfo-notebook-buttons" align="left">
  <td>
    <a target="_blank" href="https://colab.research.google.com/github/Ali-Alameer/NLP/blob/main/week7_text_embedding.ipynb"><img src="https://www.tensorflow.org/images/colab_logo_32px.png" />Run in Google Colab</a>
  </td>
</table>

## nnlm-en-dim50

## Overview

Token based text embedding trained on English Google News 7B corpus.
Text embedding based on feed-forward Neural-Net Language Models[1] with pre-built OOV. Maps from text to 50-dimensional embedding vectors.

Details
Based on NNLM with two hidden layers.

Input
The module takes a batch of sentences in a 1-D tensor of strings as input.

Preprocessing
The module preprocesses its input by splitting on spaces.

Out of vocabulary tokens
Small fraction of the least frequent tokens and embeddings (~2.5%) are replaced by hash buckets. Each hash bucket is initialized using the remaining embedding vectors that hash to the same bucket.

Sentence embeddings
Word embeddings are combined into sentence embedding using the sqrtn combiner (see tf.nn.embedding_lookup_sparse).

References
[1] Yoshua Bengio, Réjean Ducharme, Pascal Vincent, Christian Jauvin. A Neural Probabilistic Language Model. Journal of Machine Learning Research, 3:1137-1155, 2003.

In [1]:
import tensorflow_hub as hub

In [2]:
embed = hub.load("https://tfhub.dev/google/nnlm-en-dim50/2")
embeddings = embed(["cat is on the mat", "dog is in the fog"])
embeddings

<tf.Tensor: shape=(2, 50), dtype=float32, numpy=
array([[ 0.16589954,  0.0254965 ,  0.1574857 ,  0.17688066,  0.02911299,
        -0.03092718,  0.19445257, -0.05709129, -0.08631689, -0.04391516,
         0.13032274,  0.10905275, -0.08515751,  0.01056632, -0.17220995,
        -0.17925954,  0.19556305,  0.0802278 , -0.03247919, -0.49176937,
        -0.07767699, -0.03160921, -0.13952136,  0.05959712,  0.06858718,
         0.22386682, -0.16653948,  0.19412343, -0.05491862,  0.10997339,
        -0.15811177, -0.02576607, -0.07910853, -0.258499  , -0.04206644,
        -0.20052543,  0.1705603 , -0.15314153,  0.0039225 , -0.28694248,
         0.02468278,  0.11069503,  0.03733957,  0.01433943, -0.11048374,
         0.11931834, -0.11552787, -0.11110869,  0.02384969, -0.07074881],
       [ 0.1437864 ,  0.08291595,  0.10897306,  0.04464385, -0.03630389,
        -0.12605834,  0.20263346,  0.12862863, -0.07873426, -0.01195358,
         0.0020956 , -0.03080653, -0.08019945, -0.18797135, -0.11973457,
 

## nnlm-en-dim50-with-normalization

Details
Based on NNLM with two hidden layers.

Input
The module takes a batch of sentences in a 1-D tensor of strings as input.

Preprocessing
The module preprocesses its input by removing punctuation and splitting on spaces.

Out of vocabulary tokens
Small fraction of the least frequent tokens and embeddings (~2.5%) are replaced by hash buckets. Each hash bucket is initialized using the remaining embedding vectors that hash to the same bucket.

Sentence embeddings
Word embeddings are combined into sentence embedding using the sqrtn combiner (see tf.nn.embedding_lookup_sparse).

References
[1] Yoshua Bengio, Réjean Ducharme, Pascal Vincent, Christian Jauvin. A Neural Probabilistic Language Model. Journal of Machine Learning Research, 3:1137-1155, 2003.

In [3]:
embed = hub.load("https://tfhub.dev/google/nnlm-en-dim50-with-normalization/2")
embeddings = embed(["cat is on the mat", "dog is in the fog"])
embeddings

<tf.Tensor: shape=(2, 50), dtype=float32, numpy=
array([[ 0.16589954,  0.0254965 ,  0.1574857 ,  0.17688066,  0.02911299,
        -0.03092718,  0.19445257, -0.05709129, -0.08631689, -0.04391516,
         0.13032274,  0.10905275, -0.08515751,  0.01056632, -0.17220995,
        -0.17925954,  0.19556305,  0.0802278 , -0.03247919, -0.49176937,
        -0.07767699, -0.03160921, -0.13952136,  0.05959712,  0.06858718,
         0.22386682, -0.16653948,  0.19412343, -0.05491862,  0.10997339,
        -0.15811177, -0.02576607, -0.07910853, -0.258499  , -0.04206644,
        -0.20052543,  0.1705603 , -0.15314153,  0.0039225 , -0.28694248,
         0.02468278,  0.11069503,  0.03733957,  0.01433943, -0.11048374,
         0.11931834, -0.11552787, -0.11110869,  0.02384969, -0.07074881],
       [ 0.1437864 ,  0.08291595,  0.10897306,  0.04464385, -0.03630389,
        -0.12605834,  0.20263346,  0.12862863, -0.07873426, -0.01195358,
         0.0020956 , -0.03080653, -0.08019945, -0.18797135, -0.11973457,
 

## nnlm-en-dim128-with-normalization

Details
Based on NNLM with three hidden layers.

Input
The module takes a batch of sentences in a 1-D tensor of strings as input.

Preprocessing
The module preprocesses its input by removing punctuation and splitting on spaces.

Out of vocabulary tokens
Small fraction of the least frequent tokens and embeddings (~2.5%) are replaced by hash buckets. Each hash bucket is initialized using the remaining embedding vectors that hash to the same bucket.

Sentence embeddings
Word embeddings are combined into sentence embedding using the sqrtn combiner (see tf.nn.embedding_lookup_sparse).

References
[1] Yoshua Bengio, Réjean Ducharme, Pascal Vincent, Christian Jauvin. A Neural Probabilistic Language Model. Journal of Machine Learning Research, 3:1137-1155, 2003.

In [4]:
embed = hub.load("https://tfhub.dev/google/nnlm-en-dim128-with-normalization/2")
embeddings = embed(["cat is on the mat", "dog is in the fog"])
embeddings

<tf.Tensor: shape=(2, 128), dtype=float32, numpy=
array([[ 0.27107972, -0.01055073, -0.05728397,  0.06853679, -0.08438271,
         0.22396211, -0.00247001, -0.09797598, -0.06092518,  0.01678422,
         0.0183306 , -0.02683547,  0.01987647,  0.02205245,  0.0380337 ,
         0.02345292, -0.0535214 , -0.02916854, -0.13816142,  0.255649  ,
         0.00548296,  0.08994407,  0.09702856, -0.01617393,  0.15273312,
         0.03449007,  0.05599031,  0.01964826, -0.01901525,  0.11601479,
         0.06575833, -0.03560898, -0.02412845, -0.00716866, -0.08950593,
        -0.01021391,  0.07431487, -0.10462939, -0.03951982,  0.00272066,
        -0.01468687, -0.01350653, -0.04825642,  0.03088917, -0.0448269 ,
        -0.01743765,  0.1034883 ,  0.04149228, -0.03979184,  0.03878277,
         0.15273733, -0.09228262, -0.01723959,  0.01830614, -0.02075483,
         0.0800882 , -0.08071491, -0.15573218,  0.13893387,  0.06140287,
        -0.05639812, -0.05526257, -0.02765993, -0.175832  ,  0.01034007,
 